---
title: "Data preparation"
author: "Antton Alberdi"
date: "1/7/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
wd="/Users/anttonalberdi/github/EHI_technical_considerations/"
library(tidyverse)
library(maps)
library(ggplot2)
```

## Sample map
Overview of origin of the samples

```{r sample_map}
read.csv(paste0(wd,"/data/samples.csv")) %>%
  #subset columns
  select(
    sample_id,
    specimen_species,
    specimen_order,
    specimen_class,
    capture_latitude,
    capture_longitude
  ) %>%
  #Add jitter to points
  mutate(
    capture_latitude_jitter=capture_latitude+rnorm(length(capture_latitude), mean=0, sd=0.5),
    capture_longitude_jitter=capture_longitude+rnorm(length(capture_longitude), mean=0, sd=0.5),
  ) %>%
  #Plot map  
  ggplot(.) +
    geom_map(
      data=map_data("world"),
      map = map_data("world"),
      aes(long, lat, map_id=region),
      color = "white", fill = "#cccccc", size = 0.2
    ) +
    geom_point(
      aes(x=capture_longitude_jitter,y=capture_latitude_jitter, color=specimen_order),
      alpha=0.5, size=0.5, shape=16) +
    theme_minimal() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/sample_map.pdf"),device="pdf",width=12,height=10)
```

## Sample type overview
```{r sample_type}
read.csv(paste0(wd,"/data/samples.csv")) %>%
  #subset columns
  select(
    sample_id,
    sample_type,
    specimen_species,
    specimen_order,
    specimen_class
  ) %>%
  #Simplify sample types
  mutate(sample_type = case_when(
    sample_type == "Colon mucosa" | sample_type == "Duodenum mucosa" | sample_type == "Jejunum contents" | sample_type == "Esophagus swab" | sample_type == "Duodenum contents" | sample_type == "Stomach contents" | sample_type == "Stomach mucosa" | sample_type == "Colon contents" | sample_type == "Jejunum mucosa" ~ "Gut content",
    TRUE ~ sample_type
  )) %>%
  #Filter
  filter(!(sample_type %in% c("Other", "Unknown",""))) %>%
  #Aggretate data
  group_by(sample_type, specimen_order) %>%
  summarize(count = n()) %>%
  ungroup() %>%
  #Sort types
  mutate(sample_type = factor(sample_type, levels=rev(c("Faecal","Tissue","Anal/cloacal swab","Oral swab","Gut content","Blood","Skin swab","Pouch")))) %>%
  #Plot map  
  ggplot(., aes(fill=specimen_order, y=sample_type, x=count)) +
    geom_bar(position="stack", stat="identity") +
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/sample_types.pdf"),device="pdf",width=10,height=6)
```

## Host fraction density curve
```{r host_fraction_density_swabs}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    tax_group,
    sample_type,
    bases_post_fastp,
    host_bases
  ) %>%
  #Simplify sample types
  mutate(host_percentage = (host_bases/bases_post_fastp)*100) %>%
  filter(tax_group != "Amphibians") %>%
  #filter(sample_type == "Faecal") %>%
  filter(sample_type == "Anal/cloacal swab") %>%
  #Plot map  
  ggplot(., aes(x=host_percentage, color=tax_group, fill=tax_group)) +
    ggtitle("Anal/cloacal swab")+
    geom_density(alpha = 0.1) +
    scale_color_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_fill_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/host_fraction_swabs.pdf"),device="pdf",width=8,height=5)
```

```{r host_fraction_density_swabs}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    tax_group,
    sample_type,
    bases_post_fastp,
    host_bases
  ) %>%
  #Simplify sample types
  mutate(host_percentage = (host_bases/bases_post_fastp)*100) %>%
  filter(tax_group != "Amphibians") %>%
  filter(sample_type == "Faecal") %>%
  #Plot map  
  ggplot(., aes(x=host_percentage, color=tax_group, fill=tax_group)) +
    ggtitle("Faecal")+
    geom_density(alpha = 0.1) +
    scale_color_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_fill_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/host_fraction_faecal.pdf"),device="pdf",width=8,height=5)
```

## Input DNA vs. required PCR cycles
```{r inputdna_vs_pcr_sampletype}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    library_input_dna,
    library_PCR_cycles_required,
    tax_group,
    sample_type,
  ) %>%
  #Plot map  
  ggplot(., aes(y=library_PCR_cycles_required, x=library_input_dna, colour=sample_type, group=sample_type)) +
    geom_point(alpha=0.5) +
    stat_smooth(method = "lm", formula = y ~ x, geom = "smooth") +
    scale_color_manual(values = c("#bdca50", "#AA3377")) +
    scale_x_log10() +   
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/inputdna_vs_pcr_sampletype.pdf"),device="pdf",width=6,height=4)
  ggsave(paste0(wd,"/figures/antton/inputdna_vs_pcr_sampletype.png"),device="png",width=6,height=4)
```
```{r inputdna_vs_pcr_tax_group}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    library_input_dna,
    library_PCR_cycles_required,
    tax_group,
    sample_type,
  ) %>%
  #Plot map  EE6677 < bats
  ggplot(., aes(y=library_PCR_cycles_required, x=library_input_dna, colour=tax_group, fill=tax_group, group=tax_group)) +
    geom_point(alpha=0.3) +
    stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", alpha=0.2) +
    scale_color_manual(values = c("#228833","#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_fill_manual(values = c("#228833","#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_x_log10() +   
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/inputdna_vs_pcr_tax_group.pdf"),device="pdf",width=6,height=4)
  ggsave(paste0(wd,"/figures/antton/inputdna_vs_pcr_tax_group.png"),device="png",width=6,height=4)
```

## Required PCR cycles vs. quality-filtered reads
```{r pcr_vs_lowqual_sample_type}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    library_PCR_cycles_required,
    reads_pre_fastp,
    reads_post_fastp,
    bases_pre_fastp,
    bases_post_fastp,
    tax_group,
    sample_type,
  ) %>%
  mutate(lowqual_perc_reads=(1-reads_post_fastp/reads_pre_fastp)*100) %>%
  mutate(lowqual_perc_bases=(1-bases_post_fastp/bases_pre_fastp)*100) %>%
  #Plot map  EE6677 < bats
  ggplot(., aes(y=lowqual_perc_bases, x=library_PCR_cycles_required, colour=sample_type, fill=sample_type, group=sample_type)) +
    geom_point(alpha=0.3) +
    stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", alpha=0.2) +
    scale_color_manual(values = c("#bdca50", "#AA3377")) +   
    scale_fill_manual(values = c("#bdca50", "#AA3377")) +
    scale_x_log10() +   
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/pcr_vs_lowqual_sample_type.pdf"),device="pdf",width=6,height=4)
  ggsave(paste0(wd,"/figures/antton/pcr_vs_lowqual_sample_type.png"),device="png",width=6,height=4)
```

```{r pcr_vs_lowqual_tax_group}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    library_PCR_cycles_required,
    reads_pre_fastp,
    reads_post_fastp,
    bases_pre_fastp,
    bases_post_fastp,
    tax_group,
    sample_type,
  ) %>%
  mutate(lowqual_perc_reads=(1-reads_post_fastp/reads_pre_fastp)*100) %>%
  mutate(lowqual_perc_bases=(1-bases_post_fastp/bases_pre_fastp)*100) %>%
  #Plot map  EE6677 < bats
  ggplot(., aes(y=lowqual_perc_bases, x=library_PCR_cycles_required, colour=tax_group, fill=tax_group, group=tax_group)) +
    geom_point(alpha=0.3) +
    stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", alpha=0.2) +
    scale_color_manual(values = c("#228833","#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_fill_manual(values = c("#228833","#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_x_log10() +   
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/pcr_vs_lowqual_tax_group.pdf"),device="pdf",width=6,height=4)
  ggsave(paste0(wd,"/figures/antton/pcr_vs_lowqual_tax_group.png"),device="png",width=6,height=4)
```

## Required PCR cycles vs. quality-filtered reads
```{r pcr_vs_duplicates_sample_type}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    library_PCR_cycles_required,
    host_dup_percent,
    tax_group,
    sample_type,
  ) %>%
  #Plot map  EE6677 < bats
  ggplot(., aes(y=host_dup_percent, x=library_PCR_cycles_required, colour=sample_type, fill=sample_type, group=sample_type)) +
    geom_point(alpha=0.3) +
    stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", alpha=0.2) +
    scale_color_manual(values = c("#bdca50", "#AA3377")) +   
    scale_fill_manual(values = c("#bdca50", "#AA3377")) +
    scale_x_log10() +   
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/pcr_vs_duplicates_sample_type.pdf"),device="pdf",width=6,height=4)
  ggsave(paste0(wd,"/figures/antton/pcr_vs_duplicates_sample_type.png"),device="png",width=6,height=4)
```

```{r pcr_vs_lduplicates_tax_group}
read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    library_PCR_cycles_required,
    host_dup_percent,
    tax_group,
    sample_type,
  ) %>%
  #Plot map  EE6677 < bats
  ggplot(., aes(y=host_dup_percent, x=library_PCR_cycles_required, colour=tax_group, fill=tax_group, group=tax_group)) +
    geom_point(alpha=0.3) +
    stat_smooth(method = "lm", formula = y ~ x, geom = "smooth", alpha=0.2) +
    scale_color_manual(values = c("#228833","#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_fill_manual(values = c("#228833","#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_x_log10() +   
    theme_classic() +
    theme(legend.position = "bottom")
  ggsave(paste0(wd,"/figures/antton/pcr_vs_duplicates_tax_group.pdf"),device="pdf",width=6,height=4)
  ggsave(paste0(wd,"/figures/antton/pcr_vs_duplicates_tax_group.png"),device="png",width=6,height=4)
```

#TO BE DONE

## Host fraction vs. genome size
```{r host_fraction_genome_size}

mutate_function <- function(input1, input2) {
  if (input1 == input2) {
    return("Species")
  } else if (strsplit(input1, " ")[[1]][1] == strsplit(input2, " ")[[1]][1]) {
    return("Genus")
  } else {
    return("Other")
  }
}

read.csv(paste0(wd,"/data/combined.csv")) %>%
  #subset columns
  select(
    sample_id,
    tax_group,
    sample_type,
    bases_post_fastp,
    host_bases,
    host_dup_percent,
    specimen_species,
    reference_species,
    reference_size
  ) %>%
  #Create new columns
  mutate(host_percentage = (host_bases/bases_post_fastp)*100) %>%
  mutate(reference_closeness = mapply(mutate_function, specimen_species, reference_species)) %>%
  #Filter by reference closeness
  filter(reference_closeness != "Other") %>%
  #Aggretate data
  group_by(specimen_species, reference_closeness, reference_size, tax_group) %>%
  summarize(host_percentage_avg = mean(host_percentage)) %>%
  ungroup() %>%
  mutate(seq_effort=((reference_size/1000)/(host_percentage_avg/100))) %>% #For 10X coverage
  #Plot map  
  ggplot(., aes(y=specimen_species, x=seq_effort, fill=tax_group, color=tax_group)) +
    geom_point() +
    scale_color_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    scale_fill_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
    facet_grid(tax_group ~ ., scales = "free", space = "free") +
    xlim(c(1,20))+
    theme_classic() +
    theme(legend.position = "bottom", axis.text.y=element_blank())
  ggsave(paste0(wd,"/figures/antton/host_fraction_genome_size.pdf"),device="pdf",width=8,height=5)

#Considering duplicates
read.csv(paste0(wd,"/data/combined.csv")) %>%
    #subset columns
    select(
      sample_id,
      tax_group,
      sample_type,
      bases_post_fastp,
      host_bases,
      host_dup_percent,
      specimen_species,
      reference_species,
      reference_size
    ) %>%
    #Create new columns
    mutate(host_percentage = (host_bases/bases_post_fastp)*100) %>%
    mutate(reference_closeness = mapply(mutate_function, specimen_species, reference_species)) %>%
    #Filter by reference closeness
    filter(reference_closeness != "Other") %>%
    #Aggretate data
    group_by(specimen_species, reference_closeness, reference_size, tax_group) %>%
    summarize(host_percentage_avg = mean(host_percentage), host_dup_percent_avg = mean(host_dup_percent)) %>%
    ungroup() %>%
    mutate(seq_effort=((reference_size/1000)/(host_percentage_avg/100)/(1-host_dup_percent_avg))) %>% #For 10X coverage
    #Plot map  
    ggplot(., aes(y=specimen_species, x=seq_effort, fill=tax_group, color=tax_group)) +
      geom_point() +
      scale_color_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
      scale_fill_manual(values = c("#66CCEE","#CCBB44","#EE6677","#4477AA")) +
      facet_grid(tax_group ~ ., scales = "free", space = "free") +
      xlim(c(1,20))+
      theme_classic() +
      theme(legend.position = "bottom", axis.text.y=element_blank())
    ggsave(paste0(wd,"/figures/antton/host_fraction_genome_size_dup.pdf"),device="pdf",width=8,height=5)

```
