---
title: "Data preparation"
author: "Raphael Eisenhofer"
date: "1/7/2023"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analyses by Raphael

```{r, message=FALSE}
#load libs:
library(tidyverse)
library(ggforce)
library(ggdist)
library(ggpubr)

#Set colour palette
taxa <- c(
  Amphibians = "#228833",
  Bats = "#66CCEE",
  Birds = "#CCBB44",
  Reptiles = "#EE6677",
  Rodents = "#4477AA"
  )
```

# DNA yield figures
```{r, message=FALSE, warning=FALSE}

df <- read_delim("../data/combined.tsv")

## Sample type - tax group
df %>%
  filter(sample_type != "Skin swab") %>%
  filter(extraction_concentration < 50) %>%
  ggplot(aes(x = sample_type, y = extraction_concentration, 
             )) +
  stat_halfeye(
    adjust = 0.5,
    width = 0.5,
    .width = 0,
    justification = -.55,
    point_colour = NA,
    alpha = 0.7,
    normalize = "groups"
  ) +
  geom_jitter(
    aes(colour = tax_group),
    height = 0,
    width = 0.2,
    alpha = 0.7
  ) +
  # stat_summary(
  #   fun = "mean", 
  #   geom = "crossbar", 
  #   colour = "red", 
  #   width = 0.2
  # ) +
  # stat_summary(
  #   fun = "mean",
  #   geom = "text",
  #   aes(label = round(after_stat(y), 1)),
  #   hjust = 1.75,
  #   colour = "red"
  # ) +  
  theme_classic() +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  scale_colour_manual(values = taxa) +
  labs(x = "Sample type", y = "DNA concentration (ng/uL)")

ggsave("../figures/raphael/dna_yield_sample_type.png", width = 10, height = 5)



# DNA yield vs freshness
df %>%
  filter(sample_type != "Skin swab" & sample_type != "Oral swab" & sample_type != "Tissue") %>%
  filter(sample_freshness != "NA") %>%
  filter(extraction_concentration < 50) %>%
  ggplot(aes(x = factor(sample_freshness, level=c('< 1 minute', '< 10 minutes', '< 30 minutes',
                                                  '< 1 hour', '< 3 hours', '< 6 hours')), 
             y = extraction_concentration, 
             )) +
  stat_halfeye(
    adjust = 0.5,
    width = 0.5,
    .width = 0,
    justification = -.55,
    point_colour = NA,
    alpha = 0.7,
    normalize = "groups"
  ) +
  geom_jitter(
    aes(colour = tax_group),
    height = 0,
    width = 0.2,
    alpha = 0.7
  ) +
  # stat_summary(
  #   fun = "mean", 
  #   geom = "crossbar", 
  #   colour = "red", 
  #   width = 0.2
  # ) +
  # stat_summary(
  #   fun = "mean",
  #   geom = "text",
  #   aes(label = round(after_stat(y), 1)),
  #   hjust = 1.75,
  #   colour = "red"
  # ) +  
  theme_classic() +
  facet_wrap(~sample_type, scale = "free") +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  scale_colour_manual(values = taxa) +
  labs(x = "Time until preservative buffer", y = "DNA concentration (ng/uL)")

ggsave("../figures/raphael/dna_freshness.png", width = 10, height = 5)




# DNA yield vs freezing time
df %>%
  filter(sample_type != "Skin swab" & sample_type != "Oral swab" & sample_type != "Tissue") %>%
  filter(sample_freezing != "NA") %>%
  filter(extraction_concentration < 50) %>%
  ggplot(aes(x = factor(sample_freezing, level=c('< 1 day', '< 3 days', '< 7 days',
                                                  '< 14 days', '< 21 days', '> 28 days')), 
             y = extraction_concentration, 
             )) +
  stat_halfeye(
    adjust = 0.5,
    width = 0.5,
    .width = 0,
    justification = -.55,
    point_colour = NA,
    alpha = 0.7,
    normalize = "groups"
  ) +
  geom_jitter(
    aes(colour = tax_group),
    height = 0,
    width = 0.2,
    alpha = 0.7
  ) +
  # stat_summary(
  #   fun = "mean", 
  #   geom = "crossbar", 
  #   colour = "red", 
  #   width = 0.2
  # ) +
  # stat_summary(
  #   fun = "mean",
  #   geom = "text",
  #   aes(label = round(after_stat(y), 1)),
  #   hjust = 1.75,
  #   colour = "red"
  # ) +  
  theme_classic() +
  facet_wrap(~sample_type, scale = "free") +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  scale_colour_manual(values = taxa) +
  labs(x = "Time until freezing", y = "DNA concentration (ng/uL)")

ggsave("../figures/raphael/dna_freezing.png", width = 10, height = 5)


```


### Number of sample types/distribution of host taxonomy
```{r, message=FALSE}
df <- read_delim("../data/combined.tsv")

# Sample types per tax_group
df %>%
  group_by(sample_type, tax_group) %>%
  summarise(n = n()) %>%
  ggplot(aes(x = sample_type, y = n, fill = tax_group)) +
  geom_col() +
  theme_classic()

# Keep only faecal/cloacal
df_faec_cloa <- df %>%
  filter(sample_type != "Tissue" & sample_type != "Skin swab" & sample_type != "Oral swab") %>%
  filter(singlem_fraction < 1) %>%
  filter(singlem_fraction != 0 | singlem_fraction != 0.00)

# Faecal vs cloacal singlem
df_faec_cloa %>%
  ggplot(aes(x = sample_type, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0.3, alpha = 0.6)

# Time to freezing
df_faec_cloa %>%
  ggplot(aes(x = sample_freezing, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0.3, alpha = 0.6)

# Freshness
df_faec_cloa %>%
  ggplot(aes(x = sample_freshness, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0.3, alpha = 0.6)


## Other stuff
# Extraction DNA concentration
df_faec_cloa %>%
  ggplot(aes(x = extraction_concentration, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0, alpha = 0.6)

# Lib input DNA
df_faec_cloa %>%
  ggplot(aes(x = library_input_dna, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0, alpha = 0.6)

# Host reads
df_faec_cloa %>%
  ggplot(aes(x = host_reads, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0, alpha = 0.6)

# Host dup%
df_faec_cloa %>%
  ggplot(aes(x = host_dup_percent, y = singlem_fraction, colour = tax_group)) +
  geom_jitter(height = 0, width = 0, alpha = 0.6)






## Sample types
# Lib input DNA by sample_type
df_faec_cloa %>%
  ggplot(aes(x = sample_type, y = library_input_dna, colour = tax_group)) +
  geom_jitter(height = 0, width = 0.3, alpha = 0.6)

df_faec_cloa %>%
  ggplot(aes(x = sample_type, y = extraction_concentration, colour = tax_group)) +
  geom_jitter(height = 0, width = 0.3, alpha = 0.6)

```

# Looking at poor samples in detail
```{r, echo=FALSE, warning=FALSE}
df <- read_delim("../data/combined.tsv")

df_meta <- df %>%
  filter(sample_type != "Tissue" & sample_type != "Skin swab" & sample_type != "Oral swab") 

#How many don't have singlem == 0 (i.e., didn't run)
df_meta_poor <- df_meta %>% 
  filter(singlem_fraction == 0.00)

#50 faecal, 150 clocal swabs
df_meta_poor %>%
  ggplot(aes(x = sample_type, y = host_percent, colour = tax_group)) +
  geom_jitter(width = 0.3, height = 0, alpha = 0.3) + 
  facet_wrap(~tax_group)

df_meta_poor %>%
  ggplot(aes(x = extraction_concentration, y = host_percent, colour = tax_group)) +
  geom_point(alpha = 0.3)

df_meta_poor %>%
  ggplot(aes(x = library_input_dna, y = host_percent, colour = tax_group)) +
  geom_point(alpha = 0.3)

df_meta_poor %>%
  ggplot(aes(x = host_dup_percent, y = host_percent, colour = tax_group)) +
  geom_point(alpha = 0.3)

```





